"""Initial schema

Revision ID: a5db41cb5594
Revises: 
Create Date: 2026-02-08 16:03:19.605356+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5db41cb5594'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='단지명'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='주소'),
    sa.Column('region_code', sa.String(length=20), nullable=True, comment='지역코드'),
    sa.Column('kb_complex_id', sa.String(length=50), nullable=True, comment='KB 단지 ID'),
    sa.Column('priority', sa.Enum('HIGH', 'NORMAL', 'LOW', name='prioritylevel'), nullable=True, comment='수집 우선순위'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='수집 활성화 여부'),
    sa.Column('collect_listings', sa.Boolean(), nullable=True, comment='매물 수집 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_complex_id')
    )
    op.create_index(op.f('ix_complexes_id'), 'complexes', ['id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='작업명'),
    sa.Column('job_type', sa.Enum('KB_PRICE', 'KB_LISTING', 'KB_TRANSACTION', 'MOLIT_TRANSACTION', name='jobtype'), nullable=False, comment='작업 유형'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('target_config', sa.Text(), nullable=True, comment='대상 설정 (JSON)'),
    sa.Column('cron_schedule', sa.String(length=100), nullable=True, comment='Cron 스케줄'),
    sa.Column('max_concurrency', sa.Integer(), nullable=True, comment='최대 동시 처리 수'),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True, comment='분당 요청 제한'),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISABLED', name='jobstatus'), nullable=True, comment='작업 상태'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='생성자'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crawl_jobs_id'), 'crawl_jobs', ['id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('exclusive_m2', sa.Float(), nullable=False, comment='전용면적(㎡)'),
    sa.Column('supply_m2', sa.Float(), nullable=True, comment='공급면적(㎡)'),
    sa.Column('pyeong', sa.Float(), nullable=True, comment='평형'),
    sa.Column('kb_area_code', sa.String(length=50), nullable=True, comment='KB 면적 코드'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'CANCELLED', name='runstatus'), nullable=True, comment='실행 상태'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='시작 시각'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='종료 시각'),
    sa.Column('total_tasks', sa.Integer(), nullable=True, comment='총 태스크 수'),
    sa.Column('success_count', sa.Integer(), nullable=True, comment='성공 건수'),
    sa.Column('failed_count', sa.Integer(), nullable=True, comment='실패 건수'),
    sa.Column('skipped_count', sa.Integer(), nullable=True, comment='스킵 건수'),
    sa.Column('error_summary', sa.Text(), nullable=True, comment='에러 요약 (JSON)'),
    sa.Column('quality_warnings', sa.Text(), nullable=True, comment='품질 경고 (JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True, comment='실행 트리거 (user/schedule)'),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_job_status', 'crawl_runs', ['job_id', 'status'], unique=False)
    op.create_index('idx_run_started', 'crawl_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crawl_runs_id'), 'crawl_runs', ['id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('source_listing_id', sa.String(length=100), nullable=False, comment='원천 매물 ID'),
    sa.Column('ask_price', sa.Integer(), nullable=False, comment='호가 (원)'),
    sa.Column('exclusive_m2', sa.Float(), nullable=True, comment='전용면적 (㎡)'),
    sa.Column('floor', sa.Integer(), nullable=True, comment='층'),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'REMOVED', 'UNKNOWN', name='listingstatus'), nullable=True, comment='매물 상태'),
    sa.Column('posted_at', sa.DateTime(), nullable=True, comment='등록일'),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True, comment='상태 변경일'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='데이터 소스'),
    sa.Column('fetched_at', sa.DateTime(), nullable=False, comment='수집 시각'),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False, comment='마지막 확인 시각'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_listing_id')
    )
    op.create_index('idx_listing_complex_status', 'listings', ['complex_id', 'status'], unique=False)
    op.create_index('idx_listing_fetched', 'listings', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False, comment='계약일'),
    sa.Column('price', sa.Integer(), nullable=False, comment='거래가 (원)'),
    sa.Column('exclusive_m2', sa.Float(), nullable=False, comment='전용면적 (㎡)'),
    sa.Column('floor', sa.Integer(), nullable=True, comment='층'),
    sa.Column('reported_date', sa.Date(), nullable=True, comment='신고일'),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True, comment='해제 여부'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='데이터 소스'),
    sa.Column('source_id', sa.String(length=100), nullable=True, comment='원천 ID'),
    sa.Column('fetched_at', sa.DateTime(), nullable=False, comment='수집 시각'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_complex_date', 'transactions', ['complex_id', 'contract_date'], unique=False)
    op.create_index('idx_transaction_unique', 'transactions', ['complex_id', 'contract_date', 'price', 'exclusive_m2', 'floor'], unique=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('crawl_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(length=200), nullable=False, comment='태스크 키 (complex_id, area_id 등)'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRY', 'SKIPPED', name='taskstatus'), nullable=True, comment='태스크 상태'),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='재시도 횟수'),
    sa.Column('error_type', sa.String(length=100), nullable=True, comment='에러 유형'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('error_traceback', sa.Text(), nullable=True, comment='에러 스택'),
    sa.Column('items_collected', sa.Integer(), nullable=True, comment='수집 건수'),
    sa.Column('items_saved', sa.Integer(), nullable=True, comment='저장 건수'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['crawl_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_key', 'crawl_tasks', ['task_key'], unique=False)
    op.create_index('idx_task_run_status', 'crawl_tasks', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_id'), 'crawl_tasks', ['id'], unique=False)
    op.create_table('kb_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False, comment='기준일'),
    sa.Column('general_price', sa.Integer(), nullable=True, comment='일반가 (원)'),
    sa.Column('high_avg_price', sa.Integer(), nullable=True, comment='상위평균가 (원)'),
    sa.Column('low_avg_price', sa.Integer(), nullable=True, comment='하위평균가 (원)'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='데이터 소스'),
    sa.Column('fetched_at', sa.DateTime(), nullable=False, comment='수집 시각'),
    sa.Column('payload_hash', sa.String(length=64), nullable=True, comment='원문 해시'),
    sa.Column('parser_version', sa.String(length=20), nullable=True, comment='파서 버전'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_price_fetched', 'kb_prices', ['fetched_at'], unique=False)
    op.create_index('idx_kb_price_unique', 'kb_prices', ['complex_id', 'area_id', 'as_of_date'], unique=True)
    op.create_index(op.f('ix_kb_prices_id'), 'kb_prices', ['id'], unique=False)
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('payload_type', sa.String(length=50), nullable=False, comment='payload 유형 (json/html)'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='콘텐츠 해시'),
    sa.Column('storage_path', sa.String(length=500), nullable=True, comment='저장 경로 (S3 등)'),
    sa.Column('inline_content', sa.Text(), nullable=True, comment='인라인 저장 (작은 경우)'),
    sa.Column('size_bytes', sa.Integer(), nullable=True, comment='크기 (바이트)'),
    sa.Column('compressed', sa.Boolean(), nullable=True, comment='압축 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payload_created', 'raw_payloads', ['created_at'], unique=False)
    op.create_index('idx_payload_hash', 'raw_payloads', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_payloads_id'), 'raw_payloads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_payloads_id'), table_name='raw_payloads')
    op.drop_index('idx_payload_hash', table_name='raw_payloads')
    op.drop_index('idx_payload_created', table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_index(op.f('ix_kb_prices_id'), table_name='kb_prices')
    op.drop_index('idx_kb_price_unique', table_name='kb_prices')
    op.drop_index('idx_kb_price_fetched', table_name='kb_prices')
    op.drop_table('kb_prices')
    op.drop_index(op.f('ix_crawl_tasks_id'), table_name='crawl_tasks')
    op.drop_index('idx_task_run_status', table_name='crawl_tasks')
    op.drop_index('idx_task_key', table_name='crawl_tasks')
    op.drop_table('crawl_tasks')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index('idx_transaction_unique', table_name='transactions')
    op.drop_index('idx_transaction_complex_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index('idx_listing_fetched', table_name='listings')
    op.drop_index('idx_listing_complex_status', table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_crawl_runs_id'), table_name='crawl_runs')
    op.drop_index('idx_run_started', table_name='crawl_runs')
    op.drop_index('idx_run_job_status', table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_crawl_jobs_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_complexes_id'), table_name='complexes')
    op.drop_table('complexes')
    # ### end Alembic commands ###
